### ISSUE TITLE
handle() does not exist

### ISSUE THREAD

**Issue by jringeisen** [kennethllamasares/laravel-timezones#2]
I downloaded your package and got this error:

`Method KennethLlamasares\Timezones\Console\SeedTimezones::handle() does not exist`

The SeedTimezones.php fire() method needs to be updated to handle(). I changed it and it worked perfectly, figured i'd let you know.

**Comment by johntimothybailey** [comment]
@kennethllamasares Thank you for making the changes. Can you please publish them so they are available on https://packagist.org/
